output file:
processed_DeepRegcauchy_kernel1d395.json
function:
cauchy_kernel1d
Error Cases:

Pass or Failed: 0

Related Failed Test Cases:
{'FAILED test/unit/test_loss_kernel.py::test_cauchy_kernel1d[2.2] - assert False', 'test/unit/test_loss_kernel.py::test_cauchy_kernel1d[2.2] FAILED          [100%]', 'FAILED test/unit/test_loss_kernel.py::test_cauchy_kernel1d[1] - assert False', 'test/unit/test_loss_kernel.py::test_cauchy_kernel1d[3] FAILED            [ 66%]', 'FAILED test/unit/test_loss_kernel.py::test_cauchy_kernel1d[3] - assert False', 'test/unit/test_loss_kernel.py::test_cauchy_kernel1d[1] FAILED            [ 33%]'}

All Test Cases On Generated code:
============================= test session starts ==============================
platform linux -- Python 3.7.16, pytest-6.2.3, py-1.11.0, pluggy-0.13.1 -- /home/aliredaq/anaconda3/envs/deepreg/bin/python3
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/DeepReg/DeepReg, configfile: pytest.ini
plugins: dependency-0.5.1, cov-2.11.1
collecting ... collected 3 items

test/unit/test_loss_kernel.py::test_cauchy_kernel1d[1] FAILED            [ 33%]
test/unit/test_loss_kernel.py::test_cauchy_kernel1d[3] FAILED            [ 66%]
test/unit/test_loss_kernel.py::test_cauchy_kernel1d[2.2] FAILED          [100%]

=================================== FAILURES ===================================
___________________________ test_cauchy_kernel1d[1] ____________________________

sigma = 1

    @pytest.mark.parametrize("sigma", [1, 3, 2.2])
    def test_cauchy_kernel1d(sigma):
        """
        Testing the 1-D cauchy kernel
        :param sigma: float
        :return:
        """
        tail = int(sigma * 5)
        expected = [1 / ((x / sigma) ** 2 + 1) for x in range(-tail, tail + 1)]
        expected = expected / np.sum(expected)
        got = cauchy_kernel1d(sigma)
>       assert is_equal_tf(got, expected)
E       assert False
E        +  where False = is_equal_tf(<tf.Tensor: shape=(7,), dtype=float32, numpy=\narray([0.03846154, 0.07692308, 0.1923077 , 0.3846154 , 0.1923077 ,\n       0.07692308, 0.03846154], dtype=float32)>, array([0.01376295, 0.02104922, 0.03578368, 0.07156736, 0.17891839,\n       0.35783679, 0.17891839, 0.07156736, 0.03578368, 0.02104922,\n       0.01376295]))

test/unit/test_loss_kernel.py:27: AssertionError
----------------------------- Captured stderr call -----------------------------
2025-02-13 20:43:59.766088: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2025-02-13 20:43:59.924522: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2025-02-13 20:43:59.929691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:06:00.0 name: NVIDIA GeForce RTX 3060 computeCapability: 8.6
coreClock: 1.777GHz coreCount: 28 deviceMemorySize: 11.64GiB deviceMemoryBandwidth: 335.32GiB/s
2025-02-13 20:43:59.929782: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib64:
2025-02-13 20:43:59.929846: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcublas.so.10'; dlerror: libcublas.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib64:
2025-02-13 20:43:59.946291: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2025-02-13 20:43:59.946505: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2025-02-13 20:43:59.946579: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib64:
2025-02-13 20:43:59.946640: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcusparse.so.10'; dlerror: libcusparse.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib64:
2025-02-13 20:43:59.946700: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib64:
2025-02-13 20:43:59.946708: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1753] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2025-02-13 20:43:59.946934: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-02-13 20:43:59.951116: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3393635000 Hz
2025-02-13 20:43:59.951694: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4875310 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2025-02-13 20:43:59.951707: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2025-02-13 20:43:59.952408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2025-02-13 20:43:59.952421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      
___________________________ test_cauchy_kernel1d[3] ____________________________

sigma = 3

    @pytest.mark.parametrize("sigma", [1, 3, 2.2])
    def test_cauchy_kernel1d(sigma):
        """
        Testing the 1-D cauchy kernel
        :param sigma: float
        :return:
        """
        tail = int(sigma * 5)
        expected = [1 / ((x / sigma) ** 2 + 1) for x in range(-tail, tail + 1)]
        expected = expected / np.sum(expected)
        got = cauchy_kernel1d(sigma)
>       assert is_equal_tf(got, expected)
E       assert False
E        +  where False = is_equal_tf(<tf.Tensor: shape=(19,), dtype=float32, numpy=\narray([0.01317359, 0.01624141, 0.02044177, 0.02634717, 0.03487126,\n    ...0.09120175, 0.06586793, 0.04742491, 0.03487126,\n       0.02634717, 0.02044177, 0.01624141, 0.01317359], dtype=float32)>, array([0.00464621, 0.00530348, 0.00610794, 0.00710597, 0.00836318,\n       0.00997443, 0.01208015, 0.01489333, 0.018745...1874506, 0.01489333, 0.01208015,\n       0.00997443, 0.00836318, 0.00710597, 0.00610794, 0.00530348,\n       0.00464621]))

test/unit/test_loss_kernel.py:27: AssertionError
__________________________ test_cauchy_kernel1d[2.2] ___________________________

sigma = 2.2

    @pytest.mark.parametrize("sigma", [1, 3, 2.2])
    def test_cauchy_kernel1d(sigma):
        """
        Testing the 1-D cauchy kernel
        :param sigma: float
        :return:
        """
        tail = int(sigma * 5)
        expected = [1 / ((x / sigma) ** 2 + 1) for x in range(-tail, tail + 1)]
        expected = expected / np.sum(expected)
        got = cauchy_kernel1d(sigma)
>       assert is_equal_tf(got, expected)
E       assert False
E        +  where False = is_equal_tf(<tf.Tensor: shape=(13,), dtype=float32, numpy=\narray([0.02163447, 0.02960965, 0.04239693, 0.06384046, 0.09994932,\n       0.15129314, 0.18255205, 0.15129314, 0.09994932, 0.06384046,\n       0.04239693, 0.02960965, 0.02163447], dtype=float32)>, array([0.00632558, 0.00759262, 0.00927319, 0.0115632 , 0.01478475,\n       0.01949096, 0.02667596, 0.0381963 , 0.057515...5751523,\n       0.0381963 , 0.02667596, 0.01949096, 0.01478475, 0.0115632 ,\n       0.00927319, 0.00759262, 0.00632558]))

test/unit/test_loss_kernel.py:27: AssertionError
=========================== short test summary info ============================
FAILED test/unit/test_loss_kernel.py::test_cauchy_kernel1d[1] - assert False
FAILED test/unit/test_loss_kernel.py::test_cauchy_kernel1d[3] - assert False
FAILED test/unit/test_loss_kernel.py::test_cauchy_kernel1d[2.2] - assert False
============================== 3 failed in 1.37s ===============================


Final Test Result:
============================= test session starts ==============================
platform linux -- Python 3.7.16, pytest-6.2.3, py-1.11.0, pluggy-0.13.1 -- /home/aliredaq/anaconda3/envs/deepreg/bin/python3
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/DeepReg/DeepReg, configfile: pytest.ini
plugins: dependency-0.5.1, cov-2.11.1
collecting ... collected 3 items

test/unit/test_loss_kernel.py::test_cauchy_kernel1d[1] PASSED            [ 33%]
test/unit/test_loss_kernel.py::test_cauchy_kernel1d[3] PASSED            [ 66%]
test/unit/test_loss_kernel.py::test_cauchy_kernel1d[2.2] PASSED          [100%]

============================== 3 passed in 1.18s ===============================


Initial Result:
============================= test session starts ==============================
platform linux -- Python 3.7.16, pytest-6.2.3, py-1.11.0, pluggy-0.13.1 -- /home/aliredaq/anaconda3/envs/deepreg/bin/python3
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/DeepReg/DeepReg, configfile: pytest.ini
plugins: dependency-0.5.1, cov-2.11.1
collecting ... collected 3 items

test/unit/test_loss_kernel.py::test_cauchy_kernel1d[1] PASSED            [ 33%]
test/unit/test_loss_kernel.py::test_cauchy_kernel1d[3] PASSED            [ 66%]
test/unit/test_loss_kernel.py::test_cauchy_kernel1d[2.2] PASSED          [100%]

============================== 3 passed in 1.13s ===============================
