output file:
processed_visionflow_to_image273.json
function:
flow_to_image
Error Cases:

Pass or Failed: 0

Related Failed Test Cases:
{'../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[True] FAILED', 'FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[True]', '../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[False] FAILED', 'FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[False]'}

All Test Cases On Generated code:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/vision/vision/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/vision/vision
configfile: pytest.ini
plugins: mock-3.14.0
collecting ... collected 2 items

../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[True] FAILED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[False] FAILED

=================================== FAILURES ===================================
___________________________ test_flow_to_image[True] ___________________________
/local/data0/moved_data/publishablew/vision/vision/test/test_utils.py:531: in test_flow_to_image
    assert img.shape == (2, 3, h, w) if batch else (3, h, w)
E   AttributeError: 'NoneType' object has no attribute 'shape'
__________________________ test_flow_to_image[False] ___________________________
/local/data0/moved_data/publishablew/vision/vision/test/test_utils.py:539: in test_flow_to_image
    assert_equal(expected_img, img)
E   AssertionError: None mismatch: tensor([[[  0,   2,   5,  ..., 215, 217, 218],
E            [  2,   5,   7,  ..., 217, 219, 220],
E            [  5,   7,  10,  ..., 220, 221, 222],
E            ...,
E            [ 27,  33,  39,  ..., 255, 255, 255],
E            [ 29,  35,  41,  ..., 255, 255, 255],
E            [ 30,  36,  42,  ..., 255, 255, 255]],
E   
E           [[ 52,  52,  52,  ...,   7,   5,   2],
E            [ 56,  56,  56,  ...,  10,   7,   5],
E            [ 60,  60,  60,  ...,  12,  10,   7],
E            ...,
E            [255, 255, 255,  ..., 123, 120, 117],
E            [255, 255, 255,  ..., 123, 120, 117],
E            [255, 255, 255,  ..., 123, 120, 117]],
E   
E           [[255, 255, 255,  ..., 255, 255, 255],
E            [255, 255, 255,  ..., 255, 255, 255],
E            [255, 255, 255,  ..., 255, 255, 255],
E            ...,
E            [  7,  10,  12,  ...,  15,  12,  10],
E            [  5,   7,  10,  ...,  12,  10,   7],
E            [  2,   5,   7,  ...,  10,   7,   5]]], dtype=torch.uint8) is not None
=========================== short test summary info ============================
FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[True]
FAILED ../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[False]
============================== 2 failed in 0.21s ===============================


Final Test Result:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/vision/vision/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/vision/vision
configfile: pytest.ini
plugins: mock-3.14.0
collecting ... collected 2 items

../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[True] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[False] PASSED

============================== 2 passed in 0.21s ===============================


Initial Result:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/vision/vision/venv/bin/python
cachedir: .pytest_cache
rootdir: /local/data0/moved_data/publishablew/vision/vision
configfile: pytest.ini
plugins: mock-3.14.0
collecting ... collected 2 items

../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[True] PASSED
../../../../../../local/data0/moved_data/publishablew/vision/vision/test/test_utils.py::test_flow_to_image[False] PASSED

============================== 2 passed in 0.21s ===============================
